import { registerTool } from '../core/registry.js';
import { Select }   from './Select.js';
import { Node }     from './Node.js';
import { Pen }      from './Pen.js';
import { Rect }     from './Rect.js';
import { Ellipse }  from './Ellipse.js';
import { Type }     from './Type.js';
import { TypeArea } from './TypeArea.js';
import { Zoom }     from './Zoom.js';
import { Hand }     from './Hand.js';

registerTool(new Select());
registerTool(new Node());
registerTool(new Pen());
registerTool(new Rect());
registerTool(new Ellipse());
registerTool(new Type());
registerTool(new TypeArea());
registerTool(new Zoom());
registerTool(new Hand());
